/**
 * Grid Pipeline Aesthetics
 * Curated aesthetic options for the Two-Step AI Grid Pipeline.
 * Each entry maps directly to the `aesthetic` parameter in /api/instame/grid-pipeline/plan.
 *
 * Add new entries here as more aesthetic folders are added to the reference library.
 */

export type GridPipelineAesthetic = {
  /** Unique identifier (matches aesthetic name used in the pipeline system prompt) */
  id: string;
  /** Display label shown in the UI */
  label: string;
  /** Short label for rail/chip display */
  shortLabel: string;
  /** One-line description shown on the card */
  tagline: string;
  /** Suggested default palette to pre-fill in the form */
  defaultPalette: string;
  /** Suggested default light type */
  defaultLightType: string;
  /** Ionicon name for the card icon */
  icon: string;
  /** Accent color (hex) */
  accent: string;
  /** Three-stop gradient for card background */
  gradient: [string, string, string];
  /**
   * Vocabulary used in system prompts to anchor Gemini Flash's shot descriptions.
   * These keywords are injected when the user selects this aesthetic.
   */
  promptKeywords: string[];
};

export const GRID_PIPELINE_AESTHETICS: GridPipelineAesthetic[] = [
  {
    id: "Dark Academia",
    label: "Dark Academia",
    shortLabel: "Dark Acad.",
    tagline: "Moody libraries, candlelight, scholarly vintage energy.",
    defaultPalette: "deep brown, charcoal, burgundy, aged ivory, dark wood",
    defaultLightType: "warm candlelight glow, moody amber library light",
    icon: "book-outline",
    accent: "#C2A46E",
    gradient: [
      "rgba(80,55,30,0.82)",
      "rgba(50,30,18,0.90)",
      "rgba(10,8,5,0.97)",
    ],
    promptKeywords: [
      "antique library shelves",
      "vintage leather armchairs",
      "candle glow",
      "dark wood paneling",
      "scholarly architecture",
      "moody editorial",
      "aged paper texture",
      "burgundy velvet",
      "wrought iron details",
      "intellectual refinement",
    ],
  },
  {
    id: "Desert Oasis Luxury",
    label: "Desert Oasis Luxury",
    shortLabel: "Desert Oasis",
    tagline: "Terracotta, sunlit pools, warm arid luxury.",
    defaultPalette: "terracotta, sandy beige, dusty rose, warm gold",
    defaultLightType: "golden desert hour, warm haze, sun-drenched",
    icon: "sunny-outline",
    accent: "#E2A96B",
    gradient: [
      "rgba(180,110,55,0.72)",
      "rgba(130,75,30,0.88)",
      "rgba(20,12,6,0.96)",
    ],
    promptKeywords: [
      "desert resort",
      "clay and adobe walls",
      "palm tree shadows",
      "rattan and wicker",
      "infinity pool",
      "warm arid luxury",
      "sand dune backdrop",
      "Moroccan tilework",
      "linen and cotton",
      "golden hour haze",
    ],
  },
  {
    id: "Luxury European Lifestyle",
    label: "Luxury European Lifestyle",
    shortLabel: "European Luxe",
    tagline: "Parisian streets, Italian piazzas, champagne lifestyle.",
    defaultPalette: "warm beige, soft white, cobblestone grey, champagne",
    defaultLightType: "soft European afternoon light, golden Parisian glow",
    icon: "wine-outline",
    accent: "#D4B896",
    gradient: [
      "rgba(160,130,90,0.62)",
      "rgba(90,70,45,0.86)",
      "rgba(8,7,5,0.96)",
    ],
    promptKeywords: [
      "Parisian boulevard",
      "Italian piazza",
      "luxury boutique façade",
      "café terrasse",
      "cobblestone street",
      "European architecture",
      "fashion week energy",
      "ornate balcony",
      "champagne and croissants",
      "old-world elegance",
    ],
  },
  {
    id: "Minimalist Scandinavian Wellness",
    label: "Minimalist Scandinavian Wellness",
    shortLabel: "Scandi Wellness",
    tagline: "Clean whites, birch wood, hygge and Nordic calm.",
    defaultPalette: "crisp white, ash grey, soft beige, warm birch, sage",
    defaultLightType: "soft diffused Nordic daylight, clean natural light",
    icon: "leaf-outline",
    accent: "#A8BBA8",
    gradient: [
      "rgba(140,160,140,0.44)",
      "rgba(80,100,80,0.72)",
      "rgba(10,14,10,0.96)",
    ],
    promptKeywords: [
      "clean white minimalist interior",
      "natural birch wood",
      "hygge atmosphere",
      "wellness retreat",
      "organic linen textures",
      "Nordic simplicity",
      "stone and concrete",
      "indoor plants",
      "floor-to-ceiling windows",
      "calm and intentional",
    ],
  },
  {
    id: "Old Money Luxury",
    label: "Old Money Luxury",
    shortLabel: "Old Money",
    tagline: "Quiet luxury, tailored elegance, understated wealth.",
    defaultPalette: "muted beige, ivory, warm grey, navy, camel",
    defaultLightType: "soft golden afternoon, understated diffused light",
    icon: "diamond-outline",
    accent: "#C8B89A",
    gradient: [
      "rgba(150,130,100,0.58)",
      "rgba(80,65,40,0.86)",
      "rgba(8,7,5,0.96)",
    ],
    promptKeywords: [
      "quiet luxury",
      "heritage architectural details",
      "tailored silhouettes",
      "classic European manor",
      "equestrian references",
      "understated wealth",
      "cashmere and silk",
      "monogrammed accessories",
      "private members club",
      "refined restraint",
    ],
  },
  {
    id: "Amalfi Coast Vibe",
    label: "Amalfi Coast Vibe",
    shortLabel: "Amalfi Coast",
    tagline: "Clifftops, lemon groves, azure water and Italian summer light.",
    defaultPalette: "azure blue, terracotta, lemon yellow, whitewash, bougainvillea pink",
    defaultLightType: "bright Mediterranean midday, warm golden coastal glow",
    icon: "boat-outline",
    accent: "#6BBDE2",
    gradient: [
      "rgba(60,130,180,0.62)",
      "rgba(30,80,120,0.86)",
      "rgba(5,10,18,0.97)",
    ],
    promptKeywords: [
      "Amalfi cliffside terraces",
      "lemon groves and citrus detail",
      "azure Mediterranean water",
      "whitewashed walls with bougainvillea",
      "ceramic tile patterns",
      "boat deck on turquoise bay",
      "Italian coastal village alleys",
      "sun-soaked summer editorial",
    ],
  },
  {
    id: "French Riviera Vintage Summer",
    label: "French Riviera Vintage Summer",
    shortLabel: "French Riviera",
    tagline: "Saint-Tropez harbor, vintage yachts and 60s Riviera glamour.",
    defaultPalette: "sandy gold, navy, cream, coral, faded blue",
    defaultLightType: "warm Riviera afternoon, vintage film-grain light",
    icon: "umbrella-outline",
    accent: "#F5C97A",
    gradient: [
      "rgba(190,155,80,0.60)",
      "rgba(100,80,30,0.86)",
      "rgba(8,7,4,0.97)",
    ],
    promptKeywords: [
      "Saint-Tropez harbor",
      "vintage yacht deck",
      "retro straw hat and sunglasses",
      "marinière stripe detail",
      "golden sandy beach",
      "pastel parasol shade",
      "French Riviera promenade",
      "60s summer film grain",
    ],
  },
  {
    id: "Private Jet & Executive",
    label: "Private Jet & Executive",
    shortLabel: "Private Jet",
    tagline: "Jet interiors, runways, executive power dressing at altitude.",
    defaultPalette: "charcoal, ivory, champagne, polished steel, warm black",
    defaultLightType: "aircraft window golden hour, cool aviation ambient light",
    icon: "airplane-outline",
    accent: "#D4C9A8",
    gradient: [
      "rgba(70,65,55,0.72)",
      "rgba(35,32,24,0.90)",
      "rgba(5,5,3,0.97)",
    ],
    promptKeywords: [
      "private jet interior leather seat",
      "aircraft window golden hour",
      "runway tarmac boarding",
      "executive tailored power dressing",
      "luxury aviation lounge",
      "monogram luggage detail",
      "sleek jet staircase",
      "city skyline from altitude",
    ],
  },
  {
    id: "Monaco Night Drive",
    label: "Monaco Night Drive",
    shortLabel: "Monaco Night",
    tagline: "Marina lights, luxury cars, evening flash energy.",
    defaultPalette: "midnight black, deep navy, champagne gold, chrome, soft ivory",
    defaultLightType: "night flash, marina reflections, low-key luxury evening light",
    icon: "car-sport-outline",
    accent: "#8FE6FF",
    gradient: [
      "rgba(36,54,82,0.70)",
      "rgba(8,12,22,0.92)",
      "rgba(0,0,0,0.98)",
    ],
    promptKeywords: [
      "Monaco marina lights",
      "black luxury car",
      "casino entrance",
      "chrome reflections",
      "leather car interior",
      "harbor night walk",
      "flash evening portrait",
      "silk evening outfit",
      "city lights bokeh",
      "polished night drive",
    ],
  },
  {
    id: "Paris Hotel Morning",
    label: "Paris Hotel Morning",
    shortLabel: "Paris Morning",
    tagline: "Balcony coffee, tailored lounge styling, soft hotel daylight.",
    defaultPalette: "ivory, warm beige, soft grey, muted gold, cream",
    defaultLightType: "soft Parisian morning window light, warm hotel daylight",
    icon: "business-outline",
    accent: "#E7D6BE",
    gradient: [
      "rgba(222,204,176,0.58)",
      "rgba(120,100,78,0.78)",
      "rgba(16,12,9,0.96)",
    ],
    promptKeywords: [
      "Paris hotel balcony",
      "cream knit lounge set",
      "room service tray",
      "croissant and espresso",
      "marble vanity",
      "French window light",
      "ornate balcony railing",
      "tailored cardigan",
      "hotel corridor",
      "soft morning city view",
    ],
  },
  {
    id: "Milan Street Editorial",
    label: "Milan Street Editorial",
    shortLabel: "Milan Street",
    tagline: "Tailored city movement, boutique facades, fashion-week polish.",
    defaultPalette: "charcoal, cream, espresso, muted burgundy, stone grey",
    defaultLightType: "crisp European street daylight, polished editorial city light",
    icon: "walk-outline",
    accent: "#C9D3E8",
    gradient: [
      "rgba(80,86,98,0.66)",
      "rgba(38,39,45,0.90)",
      "rgba(5,5,8,0.98)",
    ],
    promptKeywords: [
      "Milan street architecture",
      "tailored oversized blazer",
      "fashion week crosswalk",
      "luxury boutique facade",
      "structured leather handbag",
      "stone sidewalk",
      "espresso bar corner",
      "sleek sunglasses",
      "editorial city walk",
      "Italian fashion district",
    ],
  },
  {
    id: "Ski Chalet Luxe",
    label: "Ski Chalet Luxe",
    shortLabel: "Ski Chalet",
    tagline: "Alpine warmth, cashmere textures, fireplace apres-ski mood.",
    defaultPalette: "cream, pine green, chocolate brown, warm amber, snow white",
    defaultLightType: "warm fireplace glow, soft alpine window light",
    icon: "snow-outline",
    accent: "#F1D8B8",
    gradient: [
      "rgba(112,86,62,0.64)",
      "rgba(40,30,24,0.90)",
      "rgba(7,6,5,0.98)",
    ],
    promptKeywords: [
      "alpine chalet interior",
      "fireplace lounge",
      "cashmere knit texture",
      "snowy window view",
      "pine wood walls",
      "apres-ski outfit",
      "wool scarf detail",
      "hot drink still-life",
      "mountain lodge sofa",
      "warm amber cabin light",
    ],
  },
  {
    id: "Gallery Date Muse",
    label: "Gallery Date Muse",
    shortLabel: "Gallery Muse",
    tagline: "Modern museum light, sculptural poses, cultured minimalist style.",
    defaultPalette: "gallery white, stone grey, matte black, soft taupe",
    defaultLightType: "clean museum daylight, soft gallery spot lighting",
    icon: "color-palette-outline",
    accent: "#DAD7CE",
    gradient: [
      "rgba(150,148,140,0.50)",
      "rgba(62,62,60,0.82)",
      "rgba(7,7,7,0.98)",
    ],
    promptKeywords: [
      "modern art gallery",
      "sculptural pose",
      "minimal black dress",
      "marble floor",
      "framed abstract artwork",
      "museum bench",
      "clean white walls",
      "soft gallery lighting",
      "stone sculpture detail",
      "cultured date mood",
    ],
  },
  {
    id: "Champagne Brunch Club",
    label: "Champagne Brunch Club",
    shortLabel: "Brunch Club",
    tagline: "Terrace brunch, glassware, flowers, polished daytime glow.",
    defaultPalette: "blush, champagne, ivory, soft green, warm linen",
    defaultLightType: "sunlit terrace daylight, bright polished brunch light",
    icon: "restaurant-outline",
    accent: "#FFD2BA",
    gradient: [
      "rgba(255,198,170,0.52)",
      "rgba(130,78,58,0.78)",
      "rgba(17,10,8,0.96)",
    ],
    promptKeywords: [
      "terrace brunch table",
      "champagne glass",
      "fresh flower arrangement",
      "linen table setting",
      "pastry plate",
      "polished daytime outfit",
      "sunlit cafe terrace",
      "delicate glassware",
      "soft greenery",
      "social brunch moment",
    ],
  },
  {
    id: "Balletcore Soft Glam",
    label: "Balletcore Soft Glam",
    shortLabel: "Balletcore",
    tagline: "Satin ribbons, pearl details, soft studio femininity.",
    defaultPalette: "dusty rose, pearl white, soft grey, champagne, ballet pink",
    defaultLightType: "soft diffused studio light, gentle romantic glow",
    icon: "sparkles-outline",
    accent: "#F2C9D8",
    gradient: [
      "rgba(230,175,196,0.54)",
      "rgba(116,74,90,0.78)",
      "rgba(18,9,14,0.96)",
    ],
    promptKeywords: [
      "satin ballet ribbon",
      "pearl accessory",
      "wrap cardigan",
      "ballet flats",
      "soft studio backdrop",
      "delicate pose",
      "tulle texture",
      "champagne highlight",
      "romantic closeup",
      "polished soft glam",
    ],
  },
  {
    id: "Rooftop Golden Hour",
    label: "Rooftop Golden Hour",
    shortLabel: "Rooftop Gold",
    tagline: "Skyline light, sunset polish, elevated evening energy.",
    defaultPalette: "amber, cream, black, sunset peach, warm gold",
    defaultLightType: "golden hour rooftop sunset, warm city backlight",
    icon: "sunny-outline",
    accent: "#FFC46F",
    gradient: [
      "rgba(230,152,74,0.58)",
      "rgba(106,60,35,0.82)",
      "rgba(12,7,5,0.96)",
    ],
    promptKeywords: [
      "rooftop skyline",
      "golden hour backlight",
      "silk evening dress",
      "city railing",
      "cocktail glass",
      "sunset wind movement",
      "warm skyline bokeh",
      "elevated terrace",
      "black evening outfit",
      "amber city glow",
    ],
  },
  {
    id: "Bridal Weekend Glow",
    label: "Bridal Weekend Glow",
    shortLabel: "Bridal Glow",
    tagline: "Pearls, white tailoring, champagne prep, celebration details.",
    defaultPalette: "white, pearl, blush, silver, soft ivory",
    defaultLightType: "bright hotel suite daylight, soft celebration glow",
    icon: "heart-outline",
    accent: "#F7DDE8",
    gradient: [
      "rgba(245,222,232,0.54)",
      "rgba(140,98,114,0.78)",
      "rgba(18,9,13,0.96)",
    ],
    promptKeywords: [
      "bridal hotel suite",
      "white tailored mini dress",
      "pearl earrings",
      "champagne toast",
      "bouquet detail",
      "silver accessories",
      "hotel mirror moment",
      "soft blush flowers",
      "celebration prep",
      "clean bridal weekend",
    ],
  },
  {
    id: "CEO Airport Uniform",
    label: "CEO Airport Uniform",
    shortLabel: "CEO Airport",
    tagline: "Airport lounge tailoring, carry-on details, executive travel calm.",
    defaultPalette: "black, camel, white, brushed steel, warm grey",
    defaultLightType: "cool airport lounge light, clean executive travel daylight",
    icon: "airplane-outline",
    accent: "#D7CAB9",
    gradient: [
      "rgba(108,96,82,0.64)",
      "rgba(40,36,34,0.90)",
      "rgba(5,5,5,0.98)",
    ],
    promptKeywords: [
      "premium airport lounge",
      "structured blazer",
      "carry-on suitcase",
      "boarding gate walk",
      "espresso cup",
      "brushed steel detail",
      "executive travel outfit",
      "passport holder",
      "quiet luxury commute",
      "airport window light",
    ],
  },
];

/** Returns an aesthetic by its id, or undefined */
export function getGridPipelineAestheticById(
  id: string,
): GridPipelineAesthetic | undefined {
  return GRID_PIPELINE_AESTHETICS.find((a) => a.id === id);
}
